spring.datasource.url=${AUTH_DATASOURCE_URL:jdbc:postgresql://localhost:5432/codeforge_auth}
spring.datasource.username=${AUTH_DATASOURCE_USERNAME:codeforge}
spring.datasource.password=${AUTH_DATASOURCE_PASSWORD:codeforge}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
