apiVersion: v1
kind: Secret
metadata:
  name: auth-service-secret
  namespace: codeforge
type: Opaque
stringData:
  AUTH_DATASOURCE_USERNAME: codeforge
  AUTH_DATASOURCE_PASSWORD: codeforge
  AUTH_JWT_SECRET: codeforge-authentication-service-kubernetes-secret-change-before-production
