package com.codeforge.authentication_service.domain

enum class AuditEventType {
    REGISTRATION,
    LOGIN_SUCCESS,
    LOGIN_FAILURE,
    OTP_SENT,
    OTP_VERIFIED,
    PASSWORD_RESET_REQUESTED,
    PASSWORD_RESET_COMPLETED,
    PASSWORD_CHANGED,
    TOKEN_REFRESHED,
    LOGOUT,
    LOGOUT_ALL,
    DEVICE_REGISTERED,
    DEVICE_REVOKED,
    USER_DISABLED,
    USER_ENABLED,
    USER_DELETED,
    ACCOUNT_LOCKED,
    ACCOUNT_UNLOCKED,
    MFA_REQUIRED,
    MFA_VERIFIED
}
